# core_categories.py
CORE_CATEGORIES = {
    # Separate ML Visualization from general visualization
    'VISUALIZATION_BASICS': [
        'HISTOGRAM', 'DISPLOT', 'KDEPLOT', 'VIOLINPLOT', 'BOXPLOT', 'BOXENPLOT',
        'BARPLOT', 'CATPLOT', 'COUNTPLOT', 'POINTPLOT', 'PIECHART',
        'SCATTERPLOT', 'LINEPLOT', 'HEXBIN', 'PAIRPLOT', 'JOINTPLOT',
        'HEATMAP', 'POLARPLOT', '3DPLOT', 'IMAGEVISUALIZATION'
    ],
    
    'VISUALIZATION_CONFIGURATION': [
        'SUBPLOTS', 'ANNOTATIONS', 'STYLING', 'FACETGRID', 'REGPLOT'
    ],
    
    'ML_VISUALIZATION': [
        'MLVISUALIZATION', 'REGRESSION'  # ML-specific visualization
    ],
    
    'DATA_PREPROCESSING': [
        'DATACLEANING', 'MISSINGVALUES', 'FILELOADINGSAVINGS',
        'STRINGOPERATIONS', 'TEXTPROCESSING', 'DATETIMEPROCESSING'
    ],
    
    'DATA_TRANSFORMATION': [
        'RESHAPING', 'INDEXING', 'GROUPINGAGGREGATION', 'MERGINGJOINING',
        'CREATINGFEATURES', 'CATEGORICALENCODING'
    ],
    
    'ARRAY_OPERATIONS': [
        'ARRAYOPS', 'BROADCASTING', 'VECTORIZATION', 'SPARSEMATRICES',
        'NUMPYBASICS', 'NUMPYMLPREPROCESSING'
    ],
    
    'STATISTICAL_COMPUTING': [
        'RANDOMGENERATION', 'DISTRIBUTION', 'STATISTICS',
        'LINEARALGEBRA', 'INTEGRATION', 'INTERPOLATION'
    ],
    
    'ML_MODELING': [
        'LINEARMODELS', 'CLUSTERING', 'CATEGORICAL', 'REGRESSION', 'TABULARDEEPLEARNING'
    ],
    
    'SCIENTIFIC_COMPUTING': [
        'SIGNALPROCESSING', 'SPATIAL', 'OPTIMIZATION', 'DIFFERENTIATION'
    ],
    
    'LIBRARY_FUNDAMENTALS': [
        'PANDASBASICS', 'PANDAS', 'NUMPY', 'SCIPY', 'MATPLOTLIB', 'SEABORN',
        'PANDAS+NUMPY'
    ]
}

# functional_workflows.py
FUNCTIONAL_WORKFLOWS = {
    # EDA Visualization Workflow
    'EDA_VISUALIZATION_FLOW': [
        'FILELOADINGSAVINGS', 'DATACLEANING', 'HISTOGRAM', 'SCATTERPLOT',
        'BOXPLOT', 'PAIRPLOT', 'HEATMAP', 'SUBPLOTS', 'STYLING'
    ],
    
    # Distribution Analysis Workflow
    'DISTRIBUTION_ANALYSIS_FLOW': [
        'HISTOGRAM', 'KDEPLOT', 'VIOLINPLOT', 'BOXPLOT', 'DISPLOT',
        'RANDOMGENERATION', 'DISTRIBUTION', 'STATISTICS'
    ],
    
    # Categorical Data Workflow
    'CATEGORICAL_ANALYSIS_FLOW': [
        'BARPLOT', 'CATPLOT', 'COUNTPLOT', 'HEATMAP', 'CATEGORICALENCODING',
        'GROUPINGAGGREGATION', 'PIECHART'
    ],
    
    # ML Preprocessing Workflow
    'ML_PREPROCESSING_FLOW': [
        'DATACLEANING', 'MISSINGVALUES', 'CREATINGFEATURES',
        'CATEGORICALENCODING', 'NUMPYMLPREPROCESSING', 'RESHAPING'
    ],
    
    # ML Modeling & Evaluation Workflow
    'ML_MODELING_FLOW': [
        'LINEARMODELS', 'REGRESSION', 'CLUSTERING', 'MLVISUALIZATION',
        'REGPLOT', 'STATISTICS'
    ],
    
    # Time Series Analysis Workflow
    'TIME_SERIES_FLOW': [
        'LINEPLOT', 'DATETIMEPROCESSING', 'INDEXING', 'RESHAPING',
        'INTERPOLATION', 'SIGNALPROCESSING'
    ],
    
    # Advanced Visualization Workflow
    'ADVANCED_VISUALIZATION_FLOW': [
        '3DPLOT', 'POLARPLOT', 'IMAGEVISUALIZATION', 'ANNOTATIONS',
        'FACETGRID', 'SUBPLOTS', 'STYLING'
    ],
    
    # Data Transformation Pipeline
    'DATA_TRANSFORMATION_FLOW': [
        'MERGINGJOINING', 'GROUPINGAGGREGATION', 'RESHAPING',
        'INDEXING', 'CREATINGFEATURES', 'STRINGOPERATIONS'
    ],
    
    # Array Math & Operations Workflow
    'ARRAY_MATH_FLOW': [
        'ARRAYOPS', 'BROADCASTING', 'VECTORIZATION', 'LINEARALGEBRA',
        'INTEGRATION', 'DIFFERENTIATION', 'OPTIMIZATION'
    ],
    
    # Scientific Computing Workflow
    'SCIENTIFIC_COMPUTING_FLOW': [
        'SIGNALPROCESSING', 'SPATIAL', 'INTERPOLATION',
        'OPTIMIZATION', 'INTEGRATION'
    ]
}